# panoptik

server:
    restart: always
    build: ./docker/server
    volumes_from:
        - data
    volumes:
        - "./static:/usr/share/nginx/static"
    ports:
        - "80:80"
    links:
        - "app:app"

app:
    build: ./docker/app
    ports:
        - "27615:27615"
    environment:
        APP_PORT: 27615
        NODE_ENV: "development"
    volumes:
        - ".:/src/app"
    volumes_from:
        - data
    command: supervisor -w bin -e js,jade -i docker,node_modules,src,static bin/server.js
    links:
        - "database:postgres"

database:
    image: postgres:latest
    environment:
        POSTGRES_USER: panoptik
        POSTGRES_PASSWORD: panoptik
        PGPASSWORD: panoptik
    expose:
        - "5432"
    ports:
        - "5433:5432"
    volumes_from:
        - data

data:
    build: ./docker/data
